### ISSUE TITLE
UI Planning 

### ISSUE THREAD

**Issue by martincarapia** [martincarapia/FinalProject220#3]
Figure out a rough draft of where to put buttons and such which will use the classes included in the UML drawing

[Untitled_Artwork.pdf](https://github.com/user-attachments/files/17135510/Untitled_Artwork.pdf)

Library: Tkinter

**Comment by sadams99** [comment]
[Uploading Untitled_Artwork.pdf…]()

**Comment by martincarapia** [comment]
I'm going to say we don't need inputs for date and time since that can be done backend. All they have to do is sign in and press clock in.

**Comment by martincarapia** [comment]
![image](https://github.com/user-attachments/assets/0dee1a88-9a3e-4786-b0e3-b8458c3e4203)
